### ISSUE TITLE
Check link to a relative file

### ISSUE THREAD

**Issue by ccfontes** [gaurav-nelson/asciidoc-link-check#31] opened 2023-04-25 00:17 UTC
Can we have checks for [link to relative file](https://docs.asciidoctor.org/asciidoc/latest/macros/link-macro/#link-to-a-relative-file)?

**Comment by gaurav-nelson** [comment] 2023-05-24 03:04
Closing: Duplicate of https://github.com/gaurav-nelson/asciidoc-link-check/issues/6

@ccfontes I haven't updated this in a while. However, I worked on `asciidoc-reference-check` extension for the Atom editor that can check relative links. Since Atom editor is no more, you can use https://pulsar-edit.dev/ and use the extension https://web.pulsar-edit.dev/packages/asciidoc-reference-check to check those links. 

That extension supports:

* Anchors:
  * standard anchors: `[[anchor]]` and `[[anchor, description]]`
  * bibliography anchors: `* [[[anchor]]]` or `* [[[anchor, description]]]`
  * inline anchors: `[#anchorname]` and `anchor:anchorname[description]`
* References:
  * Internal references: `<<anchorname>>` or `<<anchorname, description>>`
  * External references to `.adoc` files:
    * `<<path/to/file.adoc>>`, `<<path/to/file.adoc#section>>`, `<<path/to/file#section>>` or with an additional description (e.g. `<<path/to/file.adoc, description>>`)
    * `xref:path/to/file.adoc[description]`
  * External references to other types of files: `link:path/to/file[description]`
  * Hyperlinks using the `link:` macro (e.g. `link:URI[description]`) or without: `http://www.google.com`

**Closed as completed by gaurav-nelson** 2023-05-24 03:04 UTC
